#!/usr/bin/python

import time, datetime
from ibquery import InfoBeamerQuery

def main():
    while 1:
        ib = InfoBeamerQuery("127.0.0.1")

        # Example for atommic mode: Set 3 lines, the last one being
        # the current unix timestamp.
        con = ib.node("display/atomic").io(raw=True)
        con.write("KD9SBK IS OFF THE AIR\n%d\n" % datetime.datetime())
        con.close()

        time.sleep(1)

if __name__ == "__main__":
    main()


